### ISSUE TITLE
Insert MBG solutions logo in solar test equipment.

### ISSUE THREAD

**Issue by mehrdad2** [negareh/MetroBit#6]

**Comment by shimafaraji** [comment]
[TEST INSTRUMENT PAGE.docx](https://github.com/negareh/MetroBit/files/2824367/TEST.INSTRUMENT.PAGE.docx)

**Comment by shimafaraji** [comment]
There's an MBJ logo in this page and also some descriptions about MBJ products. Does Mr. Yarmohamadi mean both of them or just the logo?
